### ISSUE TITLE
valueflo.ws is broken

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#273] opened 2018-03-31 13:27 UTC
https://www.valueflo.ws/

Left-panel index and navigation is missing. https://valueflows.gitbooks.io/valueflows/ shows it properly.

![screenshot from 2018-03-31 08-24-30](https://user-images.githubusercontent.com/117439/38163634-032893ce-34bd-11e8-9e55-0f4335e42b32.png)

**Comment by elf-pavlik** [comment] 2018-03-31 14:34
Duplicate of #272

**Closed by elf-pavlik** 2018-03-31 14:34 UTC
Labels: bug
