### ISSUE TITLE
Agenda for meeting 2

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#56] opened 2015-10-11 13:55 UTC
* https://github.com/valueflows/valueflows/issues/52#issuecomment-147193331

**Comment by elf-pavlik** [comment] 2015-10-11 14:05
duplicate of https://github.com/valueflows/valueflows/issues/42 :wink: 
Can we also put agenda into Wiki of this repo instead of issue?

**Closed** 2015-10-11 14:07 UTC

**Comment by bhaugen** [comment] 2015-10-11 14:10
Sorry, I must not have been paying enuf attention when I started that dup...and I don't care where agendas go.
