### ISSUE TITLE
Model issue: currency unit vs currency resource type

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#17] opened 2015-04-16 18:34 UTC
This is a duplicate of [this valnet issue](https://github.com/valnet/valuenetwork/issues/367), which I will copy and paste here to get a different set of comments. Although you can comment on valnet, too, if you like.

> We got currency Units and currency Resource Types whose unit is the currency unit.
> 
> For example, in Sensorica, we got Canadian Dollars whose unit is the currency Canadian Dollars.
> 
> Something is probably wrong with this picture, but I don't know exactly what it is or how to fix it.
> 
> We also have Virtual Account Resources, Economic Events, prices, and other things measured in CAD, so the CAD currency Unit seems to be necessary, and is not always a duplication.
> 
> And then we got Payments and other Economic Events whose Resource Type is CAD the Resource Type and whose unit is CAD the currency Unit. So in that case, it is a duplication.
> 
> We may need to consult a philosopher...

I can hear @elf-pavlik laughing at this all the way from Europe...but many of us still need to be able to deal with money, unfortunately.

**Comment by bhaugen** [comment] 2015-04-16 19:59
I'm add this comment to both issues, too:

I asked Lynn, why didn't we just have Money as the Resource Type and then the currency CAD or USD or Euro or Yen or whatever would not be duplicate information.

She reminds me that a Resource Type must have a unit. That's why we have all of those currency-specific Resource Types.

**Comment by elf-pavlik** [comment] 2015-08-20 21:24
> She reminds me that a Resource Type must have a unit. That's why we have all of those currency-specific Resource Types.

a scientific (physical world based) unit? in contrast to bureaucratic (virtual - social convention based) unit

*10L of water located at certain address in NYC* (weight, gravity, geocordinates)
* Tesla S parked at certain address in Bay Area (model/make/year, geocordinates)
* 50kWh of electricity available in Berlin grid (energy, geolocation)

vs.

* 50$ on someone's digital GLS Bank account
* 50BTC on someone's digital wallet
* 30 facebook likes on a post in wall of particular fb event profile

**Comment by bhaugen** [comment] 2015-08-20 21:34
Units are fun! @elf-pavlik are you still laughing?

When I get into unit conversions, I also need to convert a 6-pack into 6 bottles, and then one bottle into however many oz or mls it contains. And then back.

@ahdinosaur wants to use http://qudt.org/ for units in the common vocab. The problem becomes that we want to be able to exchange any resource type for any other resource type, and so we need to consider all of the crazy units that may occur.

I don't know how to resolve all this stuff yet. Thus this issue.

**Comment by fosterlynn** [comment] 2015-08-20 21:48
>a scientific (physical world based) unit? in contrast to bureaucratic (virtual - social convention based) unit

Either one, what ever people want to use in their economic lives.  Although usually simpler than your examples.  :)

**Comment by bhaugen** [comment] 2015-08-20 22:13
For example: I just posted an offer on our regional Mutual Aid Network, and the choices for payment were MANs (their local internal currency), US Dollars, and Hours.

**Comment by ahdinosaur** [comment] 2015-08-21 00:32
> @ahdinosaur wants to use http://qudt.org/ for units in the common vocab.

happy with whatever works, that was only my best guess at a vocab that might work.

maybe we merge units with `ResourceTypes` and unit conversions can be modeled as an [`ExchangeType`](https://github.com/openvocab/exchange)?

**Comment by elf-pavlik** [comment] 2015-08-21 07:35
Looking at *Recipe*, *Plan*, *Reality*
![diagram](https://camo.githubusercontent.com/4e022abb6358edae8b381fedf1899d23b8eaac2e/68747470733a2f2f692e696d6775722e636f6d2f373467495935432e706e67)

To my understanding a *Recipe* should not include any **currency** and only describe inputs based on physical reality - goods and services (materials, tools, skilled human work etc.). When it comes to *Plan* and *Reality* currencies will star appear - "to **convince** someone to offer help with goods or services, we may need to use those currencies (for influencing another human / affecting this person's DECISION MAKING PROCESS".

So as long as *Recipe* doesn't involve currency and stays focused on describing requirements based on constrains grounded in physical reality, I see no problem. On the other hand, for planing currencies should appear with clear notion of multiple possible choices - "To get this resource we can use one of many from currencies which all involved parties agree to use eg. LETS, Timebanking, Chained Barter etc. - [subject for negotiaion]". When it gets to tracking past events (logging), I see use for records like "Out of those possible currencies supported by all parties, we used [details based on actual happening]"

@zippy @artbrock - curious about what you think...

**Comment by bhaugen** [comment] 2015-08-21 11:37
@ahdinosaur - I like qudt as one source for units.

@elf-pavlik - makes sense to me for recipes for making things to use physical units, but some of those will not come from qudt. E.g. packaging units: 6 bottles in a six pack, x ml in a bottle, 12 large green peppers in a case, etc.

We know one case, however, where people may want to define recipes that consist of exchanges. They don't think their processes are worth tracking. They harvest, dry, process and package medicinal and culinary herbs. Their resource flow is from one node in the network to another: from farm to drying facility, for example. A series of exchanges. Our software does not support that very well yet, but Lynn faked it.

And in real life, resource flows regularly alternate process and exchange (and process and exchange, etc). So if you want to define those in a recipe that covers several nodes, or multiple networks, the recipes will need to include exchanges.

Whether currencies need to go into a recipe that includes exchanges remains to be seen. As mentioned above, we've just faked it so far, but Lynn is working on a model for such a recipe.

Working with the Mutual Aid Network will be interesting, they might get into the kind of negotiation @elf-pavlik described.

As always, we work with real networks, and discount our own opinions (except in what networks we want to work with).

**Comment by bhaugen** [comment] 2015-08-21 11:41
@ahdinosaur - Resource Types have units in our model. And we don't do unit conversions yet. 

When I did it before (for ERP and supply chain software companies), unit conversions were not always associated with exchanges. We'll need a bunch of use cases. They slow everything down, too. So when we have the desirable problem that our networks are getting massive, unit conversions will be a disease.

**Comment by fosterlynn** [comment] 2015-08-21 13:23
@elf-pavlik  wrote:
> When it comes to Plan and Reality currencies will star appear - "to convince someone to offer help with goods or services, we may need to use those currencies (for influencing another human / affecting this person's DECISION MAKING PROCESS"

Further clarification and to simplify: The recipe layer you are looking at in the process flow picture won't have currencies on any level.  The recipe layer just says how something is created without any reference to how it is exchanged, there is no marketplace involved.  It is there so you don't have to recreate all of that definition when you make something. You can create the plan directly from the recipe, again just how we will make some of these, no exchanges.  Then we make them, using the plan to coordinate the processes.

( @bhaugen is talking about further extensions to recipes, but as pictured above and implemented now, this is just about creation.  And I don't think the extensions we've run into thus far will involve much incentivization, more like group decisions about how the network operates, the planned flow of resources within the network, which can involve exchanges between members in certain roles.  Note this herbal group is trying this new this year; last year they distributed income back to harvesters, dryers, etc. based on percentage of what selling the herbs brought in.  Sensorica has introduced internal exchanges also, like everyone who uses the new 3D printer puts 1.50/hour into the maintenance fund, and if they use printer filament that someone else purchased, they reimburse that person right away.  There's a lot of experimentation to be done in this area; we want to get to a flexible recipe that supports any definition of processes and exchanges intermixed.  And any exchange can involve a currency, or not, a decision of the network.  Usually right now it does.  But it is still more about resource flow within the network.)

**Comment by fosterlynn** [comment] 2015-08-21 14:26
@elf-pavlik I looked more closely at your earlier post, and I see Resources.  This is how we think of it - although of course all this is vocabulary up for discussion!!

>10L of water located at certain address in NYC (weight, gravity, geocordinates)
that is a resource, has some properties:
* resource type: water 
* quantity: 10
* unit: L
* location:...NYC...geocoodinates...
or could be:
* resource type: 10L bottle of water etc.
* quantity: 1
* unit: Each

>Tesla S parked at certain address in Bay Area (model/make/year, geocordinates)
a resource, with properties:
* resource type: Tesla S, model/make/year etc
* quantity: 1
* unit: Each
* location: certain address... 

> 50BTC on someone's digital wallet
a resource, with properties:
* resource type: BTC
* quantity: 50
* unit: BTC
* location???: someone's digital wallet 

This last one gets to Bob's original issue, which happens with currency to us in our model.  We ended up with the resource type and the unit being the same.  Yuck, but how to resolve?

We're not sure the best way to model the "location" yet either - we have created "virtual accounts" as resources of type "virtual account", and use location as the actual bank account.  (Sensorica has the situation of different people and networks owning pieces of the one actual bank account.  So their virtual account is kind of like a digital wallet.)  Our resources have relationships to agents anyway, so we say someone is owner of this resource.  I don't like it much, although it's actually working fairly well in practice.  We've talked about a new class of Money Account or something like that, for the bank account or digital wallet or whatever.  But we are still up in the air on that one.  Thus far we've tried to treat currency resources in the same way as material resources, and this is important since people don't always want to use currencies in exchanges, and we want to keep a clean universal model.  But it's not a super clean fit.)

**Comment by bhaugen** [comment] 2015-08-21 14:36
Those virtual accounts, of course, would be much simpler if we were using a digital currency and transferring bits from one wallet to another. Those are for people who are using bank accounts in a bank. We don't want to get into doing electronic transfers between banks. Can o' worms. We could also do PayPal. Another can o' worms.

But so far nobody we are working with is ready to use digital currencies.

My fave for the virtual accounts is to have an "underlying resource", which is also my favorite solution for rights to use resources (where the underlying resource is the one that the right pertains to).

**Comment by elf-pavlik** [comment] 2015-08-22 02:35
> resource type: BTC
quantity: 50
unit: BTC
location???: someone's digital wallet

maybe something in lines of 

resource type: MonetaryCurrency
quantity: 50
unit: BTC
location???: someone's digital wallet

This should allow to use exchange rates for converting *MonetaryCurrency* units. Keeping in mind that conversion multiplier changes over time - unlike physical units.

I would strongly encourage to keep clear distinction between **laws of physics** based resources and **man made convention** based resources. Maybe top level sub classes could look something like

* Resource
  * TangibleResource
    * Water
    * Produce
    * Apple
  * Service
  * Currency
    * MonetaryCurrency
      * ISO4217Currency
      * MutualCreditCurrency
      * BlockchainCurrency

Currency sub class would have clear [owl:disjointWith](http://www.w3.org/TR/owl-ref/#disjointWith-def) TangibleResource and Service :warning:

**Comment by bhaugen** [comment] 2015-08-22 10:39
QUDT is pretty good for physically-based quantities (by which they mean, a numerical value and a unit). They also specify Systems of Quantities and Systems of Units (e.g. SI). I think we could just use those for physical units, although QUDT will take some study for everybody who wants to use it - which will be a barrier to adoption. Would it be possible to simplify QUDT: extract what we need, referring to the source?

Maybe we could also adopt the idea of systems of units (e.g. MonetaryCurrency, Packaging).

Then maybe we could couple ResourceType families with systems of units.

I've also, in the past, used something like what QUDT calls "quantity kind': "The kind attribute of a quantity identifies the observable property quantified, e.g. length, force, frequency; the magnitude of the quantity expresses its relative size compared to other quantities of the same kind." In the current NRP model, we call that UnitType, and we don't model Quantity as a combination of numeric value and unit. I've done this in the past. It makes conversions pretty easy to code, but slows everything down because a number is now not a primitive anymore.

**Comment by bhaugen** [comment] 2015-08-22 11:52
Another outlier in the world of units: the [Guerrilla Translators](http://www.guerrillatranslation.org/) use Words.

**Comment by elf-pavlik** [comment] 2015-08-22 14:02
for units I also found https://iotdb.org/pub/iot-unit.html some time ago

**Comment by zippy** [comment] 2015-08-22 14:02
In the MetaCurrency world-view, we make some distinctions about the kind
measurement type that's appropriate to use depending on the systemic level
of value we are dealing with.  From what I've seen in this discussion, the
word "Resource" is too general and hides these distinctions, which leads to
some of the issues showing up in this discussion.  So, for example, a
forest can be a "resource" in which you use rational numbers to measure the
board/feet extract-able from it.  But it's also a recreation resource
(hiking and camping), which you might measure with ordinals (i.e. ranking
it against other recreational resources).  And it's also an "ecosystem
services" resource which is only reasonably measurable nominally (with
names), i.e. as a complex set of descriptions of systemic health.  Another
example we often use is the "resource" of blood.  When you treat it as
something trade-able, then you measure it in pints.  When you are about to
get a transfusion, then you must also measure its "type".  This is the
"properties of systems" for which rational numbers don't make sense.

So it's not surprising to me that monetary currencies show up oddly as a
special case in your system.  Monetary currencies, are best used to map
that lowest level of systemic value, the trade-able (or divisible) part of
the wealth of systems.  That divisibility is part of why it makes sense to
use rational numbers (literally ratio or division) for that form of
measurement.  They work well for creating marketplaces for extract-able
value, for board/feet, pints of blood, pounds of beef, person-hours, etc.
Because we've reified these maps of value and so confused them as to think
they are actual territory, we have become forced to treat them as a
resource in themselves, when they aren't.  I liked where Elf was going with
his resource hierarchy, because it hints at the levels of systemic
integrity by separating out Service from Tangible Resource.

However, I would continue to make this more explicit and classify resources
by their systemic level, or at least by the appropriate measurement type
for how that resource shows up systemically.  "Tangible" doesn't make much
sense to me because what does "touchable" mean?  The forest as recreation
is just as tangible as the forest as board-feet.  I go into the forest to
touch and be touched by it at all levels.  Typically people use "tangible"
to refer to something that's not subjective.  But I think difference is
really about "extracting" or "trading."  You can trade or extract board
feet from the forest, but you can't extract it's recreation-quality.  My
blood type is perfectly tangible, i.e. it's directly visible and
non-subjective, but it's not trade-able.  This is, I think, is the more
important distinction to make in any conversation about value, and
certainly for any system that maps value.

You can trade monetary currency, or movie tickets, or postage stamps, so
they go right there in the same category as Water.  I would just call all
of those "Issued Tokens."  Monetary currencies are just a generalized
issued tokens, whereas movie tickets and postage stamps have a more limited
use.  Then, under "Issued Tokens" you would use a Unit that matches what
they are issued for, with monetary currencies in part being created for the
purpose of having a unit, i.e. they create their own unit, whereas the unit
for movie tickets is "seat" and postage stamps is a monetary currency.

Here's an image we often use to describe the different levels of systems:
http://mail.geekgene.com/media/Levels-of-Wealth_Water.png

-Eric

**Comment by zippy** [comment] 2015-08-22 14:16
Hi Bob, as my previous post indicates, I don't think that's an outlier at
all.  I see it as intrinsic to the nature of systems.  Words are one of the
most effective ways we currently have for "measuring" i.e. recording the
value, of the more higher levels of systems, i.e. the level of
relationships between systems.  Any value mapping system will have to make
room for them when trying to map the value of "resources" at that level.

-e

**Comment by bhaugen** [comment] 2015-08-22 14:23
Don't get me wrong, we love Words as a unit. The GTs plan on using our
software, and we've designed recipes for them using words as the
measurement.

On Sat, Aug 22, 2015 at 9:16 AM, Eric Harris-Braun <notifications@github.com

**Comment by bhaugen** [comment] 2015-08-22 15:09
Forest is a good use case.

It's common for resources to change form. 

So timber (as in extractable board feed in a woodlot) is a different resource type from forest.

Likewise logs, sawn lumber, dried lumber, flooring, furniture, etc etc.

I'm not sure how to classify the recreational or ecological values. Both are clearly important.  We want economic flows to be parts of ecosystems, and are looking at [Odum's Energy Systems Language](https://en.wikipedia.org/wiki/Energy_Systems_Language) as a guide for how to go there.

**Comment by fosterlynn** [comment] 2015-08-23 18:43
I need to study this more.  In the meantime, a couple small comments in this promising discussion.

@elf-pavlik I like the notion of your hierarchy, at least to a certain extent where there is different broad behavior, and refined through this type of discussion.  Although as we have discussed before, subclassing can get cumbersome when you are down at the level of a case of 6mm screws on pallet 1 etc.  So somewhere in there, we may need the ResourceType concept.

@zippy Very interesting. Like @bhaugen , I also like the thinking that leads us to not just define resources in human economic terms, but in interconnected ecosystem terms.

**Comment by elf-pavlik** [comment] 2015-08-23 19:48
> Although as we have discussed before, subclassing can get cumbersome when you are down at the level of a case of 6mm screws on pallet 1 etc. So somewhere in there, we may need the ResourceType concept.

@fosterlynn what do you think about
* https://schema.org/TypeAndQuantityNode
* https://schema.org/includesObject

Going with types beyond *Screw* or whatever one could find in something like DBPedia based [Product Types Ontology](http://www.productontology.org/) or [AGROVOC Multilingual agricultural thesaurus](http://aims.fao.org/vest-registry/vocabularies/agrovoc-multilingual-agricultural-thesaurus) doesn't sound appealing to me. Quantities (with units), location, packaging details etc. all don't seem to me appropriate as an element of something which gets used as one of [rdf:type](http://www.w3.org/TR/rdf-schema/#ch_type) values.

**Comment by elf-pavlik** [comment] 2015-08-23 22:07
I guess all the *Currency* related conversations can now stay in https://github.com/openvocab/exchange :smile: 

IMO currencies will find their main function somewhere around **Negotiaion** phase of mentioned by you [Exchange Protocols](https://github.com/openvocab/exchange#exchange-protocols)

**Comment by bhaugen** [comment] 2015-08-23 22:16
Yeah, currencies go with exchanges. But in actualization as well as
negotiation (per the ISO phases).

**Comment by fosterlynn** [comment] 2015-08-28 15:30
> what do you think about
    https://schema.org/TypeAndQuantityNode
    https://schema.org/includesObject

@elf-pavlik Sorry I have not responded to this.  Will do so eventually, but I need to think about it in terms of all resources and resource types, bigger discussion.  Maybe a separate openvocab repo for Resource?

**Comment by bhaugen** [comment] 2015-08-28 23:01
What @fosterlynn said.

**Comment by elf-pavlik** [comment] 2015-08-28 23:30
I would say let's don't rush with extracting too many repositories, unless you feel very strong about doing it. Also for such logistic we can continue in https://github.com/openvocab/ovn/issues/23 and try to keep this one focused on original subject. I'll try to think tomorrow on what we can clearly define as [owl:disjointWith](http://www.w3.org/TR/2012/REC-owl2-primer-20121211/#a_DisjointClasses) which could help with organizing different work streams.

**Comment by elf-pavlik** [comment] 2019-01-30 17:52
I'll make PR with an example which uses
* `resourceClassifiedAs`
* `unit:Number`

**Comment by fosterlynn** [comment] 2019-10-06 23:39
duplicate of #517

**Closed by fosterlynn** 2019-10-06 23:39 UTC
Labels: Resource, example
